# https://numtide.github.io/devshell
[devshell]
packages = [
  "dotnet-sdk_9",
  "dotnet-ef",
  "csharp-ls",
  "vscode-fhs",
  "sqlcmd",
  "nodejs_24",
]

[[commands]]
name = "tailwind"
command = "npx @tailwindcss/cli -i ./wwwroot/input.css -o ./wwwroot/output.css --watch"
